version: '2'
services:
  web:
    restart: always
    build: .
    #image: abiosoft/caddy:php
    ports:
      - 172.19.5.1:30005:2015
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./src:/app/src
      - ./.env:/app/.env
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - /app/vendor
